CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "image" varchar NOT NULL,
  "category" varchar NOT NULL,
  "description" text,
  "rating" int NOT NULL,
  "num_reviews" int NOT NULL DEFAULT 0,
  "price" decimal(10,2) NOT NULL DEFAULT 0,
  "count_in_stock" int NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  "deleted_at" timestamp
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payment_method" varchar NOT NULL,
  "tax_price" decimal(10,2) NOT NULL DEFAULT 0,
  "shipping_price" decimal(10,2) NOT NULL DEFAULT 0,
  "total_price" decimal(10,2) NOT NULL DEFAULT 0,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  "deleted_at" timestamp
);

CREATE TABLE "order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "name" varchar NOT NULL,
  "quantity" int NOT NULL,
  "image" varchar NOT NULL,
  "price" decimal(10,2) NOT NULL DEFAULT 0,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  "deleted_at" timestamp
);

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");
